export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const MARK_AS_DONE = 'MARK_AS_DONE';
export const MARK_AS_IMPORTANT = 'MARK_AS_IMPORTANT';
export const SEARCH_TERM = 'SEARCH_TERM';
export const FILTER_CONDITION = 'FILTER_CONDITION';
export const FILTER_CONDITION_ALL = 'FILTER_CONDITION_ALL';
export const FILTER_CONDITION_ACTIVE = 'FILTER_CONDITION_ACTIVE';
export const FILTER_CONDITION_DONE = 'FILTER_CONDITION_DONE';
export const FILTER_CONDITION_IMPORTANT = 'FILTER_CONDITION_IMPORTANT';
export const THEME = {
    MAIN_COLOR: '#007FFF',
    DANGER_COLOR: '#ff0000',
    SELECTED_ITEM: '#f5a0a9',
    WHITE_COLOR: '#fff',
    GREEN_COLOR: '#198754',
    BLACK_COLOR: '#000'
};